- name: Disabling NodeJS Module
  ansible.builtin.shell: dnf module disable nodejs -y

- name: Enbaling NodeJS 18 Module
  ansible.builtin.shell:  dnf module enable nodejs:18 -y

- name: Install NodeJS
  ansible.builtin.dnf:
    name: nodejs
    state: present

- name: Copying backend service file
  ansible.builtin.copy:
    src: backend.service
    dest: /etc/systemd/system/backend.service

- name: Adding Application user
  ansible.builtin.user:
    name: expense

- name: Removing old app content
  ansible.builtin.file:
    path: /app
    state: absent

- name: Creating new directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Downloading and Extracting the Backend Content
  ansible.builtin.unarchive:
    src: https://expense-artifacts.s3.amazonaws.com/backend.zip
    dest: /app
    remote_src: yes

- name: Install Nodejs Dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: /app

- name: Installing MySQL client
  ansible.builtin.dnf:
    name: mysql
    state: present

- name: To Load Schema
  ansible.builtin.shell: mysql -h mysql-dev.kgs666devops.online -uroot -p{{MYSQL_ROOT_PASSWORD}} < /app/schema/backend.sql

- name: To Start Backend Services
  ansible.builtin.systemd:
    name: backend
    state: restarted
    enabled: yes
    daemon-reload: yes
