- name: Installing nginx
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: Copy Expense Conf File
  ansible.builtin.template:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf

- name: Import Common Role- App-prerequisites
  ansible.builtin.import_role:
    name: common
    tasks_from: app-prereq
  vars:
    app_dir: /usr/share/nginx/html
    component: frontend

- name: Start nginx service
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes

- name: Import ELK Role
  ansible.builtin.import_role:
    name: elk
    tasks_from: filebeat

- name: Import Prometheus Role-Node Exporter
  ansible.builtin.import_role:
    name: prometheus
    tasks_from: node-exporter


- name: Import Grafana Dashboard
  ansible.builtin.import_role:
    name: grafana

- name: Generate Alert YAML File
  ansible.builtin.template:
    src: alert-rules.yml
    dest: /tmp/{{component}}-{{env}}.yml

#
- name:  Upload Alert File to S3
  ansible.builtin.shell:  aws s3 cp /tmp/{{component}}-{{env}}.yml s3://kgs-prometheus-alert-rules/{{component}}-{{env}}.yml
    #amazon.aws.s3_object:
    #  bucket: kgs-prometheus-alert-rules
    # object: "{{component}}-{{env}}.yml"
  #src: /tmp/{{component}}-{{env}}.yml
  #mode: put

- name: Trigger  Prometheus Reload  Job
  ansible.builtin.shell: curl -u {{ lookup('amazon.aws.aws_ssm','jenkins.username',region='us-east-1' ) }}:{{ lookup('amazon.aws.aws_ssm','jenkins.password',region='us-east-1' ) }} "http://172.31.28.219:8080/job/prometheus-reload/build?token=prometheus"





