- name: Removing old app content
  ansible.builtin.file:
    path: "{{ app_dir }}"
    state: absent

- name: Creating new directory
  ansible.builtin.file:
    path: "{{ app_dir }}"
    state: directory


- name: Downloading and Extracting the Backend Content
  ansible.builtin.unarchive:
    src: https://expense-artifacts.s3.amazonaws.com/{{component}}.zip
    dest: "{{ app_dir }}"
    remote_src: yes
