- name: Copy Prometheus Config File
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: Copy Alert Rules
  ansible.builtin.template:
    src: common.yml
    dest: /opt/prometheus/alert-rules/common.yml

##
- name: Copy Alert Rules
  ansible.builtin.template:
    src: {{component}}-{{env}}.yml
    dest: /opt/prometheus/alert-rules/{{component}}-{{env}


- name: Reload Prometheus
  ansible.builtin.shell: kill -1 $(ps -ef | grep /opt/prometheus/prometheus | grep -v grep | awk '{print $2}')


- name: Copy AlertManager File
  ansible.builtin.template:
    src: alertmanager.yml
    dest: /opt/alertmanager/alertmanager.yml

- name: Reload AlertManager
  ansible.builtin.shell: kill -1 $(ps -ef | grep /opt/alertmanager/alertmanager | grep -v grep | awk '{print $2}')
