groups:
  - name: frontend-dev
    rules:
      - alert: InstanceDown
        expr: up < 1
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Instance Down Alert